Repository jvoisin/snuffleupagus, pull requests merged in 2018-10, with the labels that each got.

#252 Fix segfault array keys
  src/sp_sloppy.c
  src/tests/sloppy_comparison_array_keys.phpt
  src/tests/sloppy_comparison_array_search_keys.phpt
Labels: crash, critical

#253 Bump a bit the coverage
  src/sp_config_keywords.c
  src/sp_cookie_encryption.c
  src/sp_crypt.c
  src/sp_disabled_functions.c
  src/sp_disabled_functions.h
  src/sp_execute.c
  src/sp_pcre_compat.c
  src/sp_session.c
  src/sp_sloppy.c
  src/sp_unserialize.c
  src/sp_upload_validation.c
  src/sp_utils.c
  src/sp_utils.h
  src/sp_var_parser.c
  src/sp_wrapper.c
  src/tests/broken_conf_cookie_encryption_without_encryption_key.phpt
  src/tests/broken_conf_cookie_encryption_without_env_var.phpt
  src/tests/broken_conf_mutually_exclusive11.phpt
  src/tests/broken_conf_mutually_exclusive12.phpt
  src/tests/broken_conf_wrapper_whitelist.phpt
  src/tests/config/broken_conf_cookie_encryption_without_encryption_key.ini
  src/tests/config/broken_conf_cookie_encryption_without_env_var.ini
  src/tests/config/broken_conf_mutually_exclusive11.ini
  src/tests/config/broken_conf_mutually_exclusive12.ini
  src/tests/config/broken_conf_wrapper_whitelist.ini
  src/tests/crypt_session_invalid.phpt
  src/tests/encrypt_cookies4.phpt
  src/tests/encrypt_cookies_empty_env.phpt
  src/tests/encrypt_cookies_invalid_decryption.phpt
  src/tests/encrypt_regexp_cookies_invalid_decryption.phpt
Labels: code cleanup, testsuite

#256 Improve mb_string hooking logic
  src/sp_utils.c
Labels: code cleanup

#255 Don't check the return values of functions that might not return
  src/sp_disabled_functions.c
  src/sp_disabled_functions.h
  src/sp_execute.c
Labels: code cleanup
