Repository jvoisin/snuffleupagus, pull requests merged in 2018-08, with the labels that each got.

#204 fix #203
  src/sp_config_keywords.c
  src/tests/broken_conf_invalid_filename.phpt
Labels: configuration, enhancement, good first issue, virtual patching

#211 Add a whitelist for php's wrappers
  doc/source/config.rst
  doc/source/features.rst
  src/config.m4
  src/php_snuffleupagus.h
  src/snuffleupagus.c
  src/sp_config.c
  src/sp_config.h
  src/sp_config_keywords.c
  src/sp_config_keywords.h
  src/sp_wrapper.c
  src/sp_wrapper.h
  src/tests/config/config_stream_wrapper.ini
  src/tests/config/config_stream_wrapper_register.ini
  src/tests/stream_wrapper.phpt
  src/tests/stream_wrapper_register.phpt
  src/tests/stream_wrapper_restore.phpt
Labels: feature

#223 Verify certs
  config/default.rules
  doc/source/config.rst
  doc/source/encryption.rst
  doc/source/features.rst
  src/config.m4
  src/php_snuffleupagus.h
  src/snuffleupagus.c
  src/sp_config.c
  src/sp_config.h
  src/sp_config_keywords.c
  src/sp_config_keywords.h
  src/sp_curl_verify_certificates.c
  src/sp_curl_verify_certificates.h
  src/tests/config/disabled_function_curl_verify_certs.ini
  src/tests/ensure_client_valid_certs.phpt
  src/tests/ensure_server_valid_certs.phpt
Labels: rules

#231 match on ret improvments
  src/sp_disabled_functions.c
  src/sp_disabled_functions.h
  src/sp_execute.c
  src/sp_utils.c
  src/sp_utils.h
  src/tests/disabled_functions_chain_call_user_func_ret.phpt
  src/tests/disabled_functions_ret_user.phpt
Labels: enhancement, usability, virtual patching

#233 Minor refactor.
  src/snuffleupagus.c
  src/sp_config.c
  src/sp_config_keywords.c
  src/sp_cookie_encryption.c
  src/sp_crypt.c
  src/sp_disabled_functions.c
  src/sp_execute.c
  src/sp_harden_rand.c
  src/sp_session.c
  src/sp_unserialize.c
  src/sp_upload_validation.c
  src/sp_utils.c
Labels: code cleanup
